# Created with YamlCreate.ps1 v2.7.1 $debug=AUSU.CRLF.7-5-4.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GitHub.Copilot
PackageVersion: 1.0.0
InstallerType: zip
Commands:
- copilot
ReleaseDate: 2025-12-30
Installers:
- Architecture: x64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: copilot.exe
  InstallerUrl: https://github.com/github/copilot-cli/releases/download/v0.0.373/copilot-win32-x64.zip
  InstallerSha256: F1C2335DFD55D5954E60293BC5B0E0AC0DE0EF219078C3D2C70F5D65F78DDFF0
- Architecture: arm64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: copilot.exe
  InstallerUrl: https://github.com/github/copilot-cli/releases/download/v0.0.373/copilot-win32-arm64.zip
  InstallerSha256: 538BB868BDE7BCFA7720F7018A30B61D6252D5FFA93E67DE4933BC2A5F515166
ManifestType: installer
ManifestVersion: 1.12.0
